### ISSUE TITLE
P360- Performance - Fairview

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#510]
Navigation delay and search performance is slow

**Additional context**
Build no :
Region :
Client :

**Comment by padminiganapathi** [comment]
@raniangamuthu : Please provide all the necessary details along with Build no, Region, priority.

**Comment by sathian123** [comment]
Hi @raniangamuthu 

Could you please share the following details to help us triage this issue further:

Navigation delay – Please provide details on how much time it takes to navigate from one screen to another, along with the specific screens between which you are facing the issue.

Search performance – Please share how much time it takes to execute the search, and also how long the same search takes to execute from the ADS side.

Note: Please share the relevant screenshots for each case.

**Comment by ThulasiP3** [comment]
@sathian123  ,As discussed with you ,For a general search The same results are fetched in different time intervals

Attached the screenshots here. 
Before applying indexes in non-prod:

<img width="1905" height="906" alt="Image" src="https://github.com/user-attachments/assets/c078f3f5-0634-4e66-9d5a-74f594e633e0" />


After applying indexes:(first time)

<img width="1910" height="872" alt="Image" src="https://github.com/user-attachments/assets/12cf42f9-beac-4401-95e7-5df981c3717e" />

Second time after reset:

<img width="1914" height="901" alt="Image" src="https://github.com/user-attachments/assets/2f0c8838-640f-4e2f-87dc-0b4b22390e62" />

Third time : 

<img width="1908" height="801" alt="Image" src="https://github.com/user-attachments/assets/1ee9c04a-74f0-4b11-8ab6-09cdf37d67b3" />


<img width="578" height="127" alt="Image" src="https://github.com/user-attachments/assets/3665c1c1-b87c-464e-a3a5-14112e2bea36" />

**Comment by ThulasiP3** [comment]
By Indexing Scenario1 and 3 has been fixed in PROD  .Scenario 2 will be tracked under #501.Good to close this issue

**Comment by raniangamuthu** [comment]
Note: we still have the slowness which is from ADS that is showing the slowness navigating between the screens in the rail

**Comment by sathian123** [comment]
Current Update on this Ticket:

Post the build release, @ThulasiP3 checked the Fairview Prod and Non-Prod environments and observed that it took almost the same time to retrieve results in both ADS and P360. Furthermore, optimization cannot be done from the P360 side. Kindly request that you attach the relevant screenshots and provide closure for this issue.

**Comment by ThulasiP3** [comment]
Based on customer feedback on performance and above screenshots as reference this issue can be closed

**Comment by raniangamuthu** [comment]
Have discussed with client and for now they haven't raised concerns so closing this issue
